version: '3'
services:
  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./web/src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=test_task
    restart: always
  app:
    build: .
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
